# Generated by Django 2.0.3 on 2018-06-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DartsRecognitionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField()),
                ('since', models.DateTimeField(verbose_name='date started')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(help_text='Is the game currently active.')),
                ('start_time', models.DateTimeField(help_text='Time the game started', null=True)),
                ('end_time', models.DateTimeField(help_text='Time the game ended.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('CR', 'Cricket'), ('501', '501'), ('301', '301'), ('KR', 'Killer')], help_text='Choose the type of game.', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Player name', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(help_text='Round of the game')),
                ('throw_number', models.IntegerField(help_text='Throw of the round')),
                ('hit', models.IntegerField(verbose_name='The number hit, 25 = BULL, 0 = Not valid')),
                ('modifier', models.IntegerField(verbose_name='Modifier for Doubles and Triples')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp of the throw')),
                ('player', models.OneToOneField(help_text='Player_id, for the throw', null=True, on_delete=django.db.models.deletion.SET_NULL, to='darts_ui.Player')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.OneToOneField(help_text='Type of this game', null=True, on_delete=django.db.models.deletion.SET_NULL, to='darts_ui.GameType'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(help_text='Players for this game', to='darts_ui.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='throws',
            field=models.ForeignKey(help_text='Throws for this game', null=True, on_delete=django.db.models.deletion.SET_NULL, to='darts_ui.Throw'),
        ),
    ]
