# Generated by Django 2.0.3 on 2018-06-20 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('darts_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(help_text='Type of this game', null=True, on_delete=django.db.models.deletion.SET_NULL, to='darts_ui.GameType'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ForeignKey(help_text='Players for this game', null=True, on_delete=django.db.models.deletion.SET_NULL, to='darts_ui.Player'),
        ),
        migrations.AlterField(
            model_name='throw',
            name='player',
            field=models.ForeignKey(help_text='Player_id, for the throw', null=True, on_delete=django.db.models.deletion.SET_NULL, to='darts_ui.Player'),
        ),
    ]
