# Generated by Django 2.0.3 on 2018-06-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts_ui', '0002_auto_20180620_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Time the game ended.', null=True),
        ),
    ]
