# Generated by Django 2.0.3 on 2018-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts_ui', '0003_auto_20180620_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(help_text='Players for this game', null=True, to='darts_ui.Player'),
        ),
    ]
