# Generated by Django 2.0.3 on 2018-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darts_ui', '0004_auto_20180621_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(help_text='Players for this game', to='darts_ui.Player'),
        ),
    ]
