# Generated by Django 2.0.3 on 2018-06-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darts_ui', '0006_auto_20180621_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('name',)},
        ),
    ]
